### ISSUE TITLE
Copy and Paste shortcuts not working on MacOS

### ISSUE THREAD

**Issue by nikitalita** [ChiriVulpes/MagicTranslator#160]
not sure if this is present on PC as well, but I can't copy or paste text with the macOS shortcuts (i.e. command + C and command + V). I have to go to the edit menu to copy and paste text.

**Comment by ChiriVulpes** [comment]
No, this bug is because on Mac you have to add cut copy paste etc to the app menu in order to get keybindings for them for some reason

**Comment by milleniumbug** [comment]
Ah, yeah, _the app menu_, the one we don't normally show on other platforms. Understandable why we didn't catch it.

**Comment by ChiriVulpes** [comment]
@nikitalita If you have time at some point can you test with the commit I just pushed? Not 100% sure it will be fixed with this, but I had a theory

**Comment by nikitalita** [comment]
no, but #165 fixes it.
