### ISSUE TITLE
Relatively fresh Linux Mint install doesn't have the spinner character

### ISSUE THREAD

**Issue by milleniumbug** [ChiriVulpes/MagicTranslator#163]
![image](https://github.com/ChiriVulpes/MagicTranslator/assets/3199994/b4afda9d-cacb-46fe-bc57-ef7256ab01a2)

It worked for me before so I probably had some fonts installed back then, but I don't do now, but I wonder if we may need to ship some, and if we do - which ones.

Update: `sudo apt install fonts-noto` gave a whole bunch of them and including handling this character.

**Comment by ChiriVulpes** [comment]
Closing in favour of #130
